Port: /dev/ttyUSB2
BaudRate: 115200
APN: lpwa.vodafone.iot
Band:
  - B20
  - B8
  - B3
Tech: LTEM
PLMN: 23003
RegTimeout: 300
CmdTimeout: 30
PWRKey: 24
Antenna: INT

Logging:
  file: ./Logs/logs.log
  level: info